### ISSUE TITLE
keyword(s) (tolerance) not recognized

### ISSUE THREAD

**Issue by miroi** [bast/runtest#10]
Hi Rado,

in the documentation, like here, https://runtest.readthedocs.io/en/latest/doc/filter_options.html#filtering-a-number-of-lines-starting-with-string-regex

you are showing unsupported keyword:
~~~
ERROR: keyword(s) (tolerance) not recognized
       available keywords: (from_re, to_re, re, from_string, to_string, string, ignore_below, ignore_above, ignore_sign, mask, num_lines, rel_tolerance, abs_tolerance)
~~~

**Comment by bast** [comment]
Thanks!
