### ISSUE TITLE
[Feature request] Incremental build-up of filters

### ISSUE THREAD

**Issue by robertodr** [bast/runtest#14]
## Description
The current way of generating filters is really convenient, since it allows to incrementally add filtering hooks:
```python
energy = Filter()
energy.add(string = 'Nuclear repulsion:',
      rel_tolerance = 1.0e-7)
energy.add(string = 'Electronic energy:',
      rel_tolerance = 1.0e-7)
energy.add(string = 'Solvation energy:',
      abs_tolerance = 1.0e-7)
```
One could use such an `energy` filter to build even more refined filters, by using it as a boilerplate base and adding more filtering hooks on top. In DALTON, one could, for example, do the following to build up a HF energy filter and a filter for a ground state plus excitation energy calculation:
```python
# Hartree-Fock energy filter
hf = energy
hf.add(string = 'Final HF energy:',
      rel_tolerance = 1.0e-7)

# HF 1PA filter
hf_1pa = hf
hf_1pa.add(string = '@ Excitation energy :',
              rel_tolerance = 1.0e-5)
hf_1pa.add(string = '@ Oscillator strength (LENGTH)',
              mask = [1],
              ignore_below = 1.0e-9,
              rel_tolerance = 1.0e-3)
```
In Python, however, the assignments `hf = energy` and `hf_1pa = hf` **do not** create new filters, but instead instances pointing to the same `energy` filter (this is intrinsic, due to garbage collection and reference counting). The workaround is to use `deepcopy`, this pattern achieves the above `hf = copy.deepcopy(energy)`

## Feature Request and Discussion
The deep copy pattern could be embedded in the `Filter` class by overloading the arithmetic `+` and `-` operators, to add/remove filtering hooks and filtering options from an existing filter. Bonus of this kind of strategy is that all the boilerplate in the small `test` scripts could be removed. In DALTON, for example, alongside the adapter script, hooking up `runtest` and the DALTON launcher script, one could have a library of filters, e.g. for the Hartree-Fock energy, for the excitation energies and oscillator strengths and so forth.

**Comment by bast** [comment]
Thanks for the suggestion. It actually refers to old runtest version :-) which is an indicator that I need to improve docs and better communicate that things have changed. But your suggestion is good and I will very soon test it with the latest version and adapt your suggestion and come back to this very soon.

**Comment by robertodr** [comment]
Oh, yes, I forgot about the new version. I stumbled upon this in DALTON, which I think still uses the old version.

**Comment by bast** [comment]
It might be relevant also for the latest so let's keep the suggestion.

**Comment by bast** [comment]
Finally catching up: So first I recommend to go for the latest code where data structures have changed - I have abandoned classes and decided to collect tests in a normal Python list: http://runtest.readthedocs.io/en/latest/creating/example.html

Now the problem that you describe is still there of course. And we could "fix" it following your suggestion. I am however not sure yet whether this would be more surprising or less surprising. Python developers will expect that a list assignment will not create a new list and they may be surprised if we do clever things under the hood. On the other hand the developers writing tests may not be Python experts and may be surprised that a copy is shallow. I am still not sure which path to follow.

**Comment by robertodr** [comment]
Finally catching up too (asynchronicity...) Lists are a great idea! :smile: I haven't tried the new version of the code, but from the example you link, the situation would be solved anyway. The incremental build up of the test would be done by extending the list, right?

**Comment by bast** [comment]
Yes, exactly.

**Comment by robertodr** [comment]
Great, closing this issue as no longer relevant. Thanks!
