### ISSUE TITLE
Extend command line arguments, how to do that ?

### ISSUE THREAD

**Issue by miroi** [bast/runtest#15]
Hi Rado !

the runtest has own set of command line arguments, described here:
https://runtest.readthedocs.io/en/latest/running/command_line_arguments.html

In the testing script, *DIRAC/test/read_all_basis_sets/test* I would like to add a new set of my own arguments, like *--bsfile=XXX --Zel=XXX ... *.

How to do that ? I think it would be good if users testing scripts could work  with extended arguments.

PS: It seems that one has to adapt the runtest code adapter, https://runtest.readthedocs.io/en/stable-1.x/doc/adapters/dirac.html  ...

**Comment by bast** [comment]
Thanks for the suggestion. I will look at it and write here my thoughts on it. Please also note that the "stable" doc refers to an old version. The latest code has moved on quite significantly. I need to clarify this.

**Comment by bast** [comment]
First of all, I strongly recommend to use the latest code: http://runtest.readthedocs.io/en/latest/ - there are few tests in DIRAC which already employ the latest runtest code.

Would it be an idea to pass the extra information via environment variables?

E.g.:
```
$ BSFILE=foo ZEL=123 /path/to/test
```
and in the test script to get these with `os.environ`?

**Comment by miroi** [comment]
I fully agree ! I forgot that it is possible to pass variables in much simpler way, through environment variables.

Also thanks for updating runtest in Dirac, now I have the space to implement it.

Closing this ticket as SOLVED.
