### ISSUE TITLE
test.run should return value

### ISSUE THREAD

**Issue by miroi** [bast/runtest#16]
Hi Rado,

for Dirac, I would need the return code of test.run, as this is necessary to evaluate which test passed and which crashed.

In previous version there was return code (this is related to https://gitlab.com/dirac/dirac/merge_requests/42 )

~~~
                   #miro: needs to use the try-except scheme because a first error in test.run ends the loop
                   try:
                       rc=test.run( ['input_test.inp'], ['element.mol'], f, args=args_str, print_args=True )
                       print "rc=",rc
                       tests_passed=tests_passed+1
                   except:
                       tests_crashed=tests_crashed+1
                       print >> sys.stderr,tests_crashed, '. CRASHED: basis set file=',basis_set_file,' element Z9Q=',str(Z9Q)
~~~

**Comment by miroi** [comment]
There is indeed return of number, https://github.com/bast/runtest/blob/master/runtest/run.py#L89 , in **run** function. But why Dirac does not show any returning value ?

**Comment by bast** [comment]
You need to return it "manually" - see an example here: http://runtest.readthedocs.io/en/latest/creating/example.html

The motivation for this was to give more flexibility at a very small expense of few extra lines.

**Comment by miroi** [comment]
Well, the new scheme gives error
~~~
  File "./test", line 173, in run_through_selected_basis_set_files
    ierr+=test.run( ['input_test.inp'], ['element.mol'], f, args=args_str, print_args=True ) 
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
~~~

**Comment by bast** [comment]
Ah sorry - I misunderstood the issue. But we are talking about runtest 2 here or runtest 1?

**Comment by miroi** [comment]
This is the recent runtest put into Dirac, so version 2, right ?

PS: Would be good to have runtest version printed for each run , like "running test (with runtest version 2.x) "

**Comment by bast** [comment]
`test.run` looks to me like old runtest - see `dft_ac` test as an example for new runtest.

**Comment by bast** [comment]
In DIRAC we have both coexisting since I wanted to give us the possibility to switch gradually.

**Comment by miroi** [comment]
Rado, in the example https://runtest.readthedocs.io/en/latest/creating/example.html I am missing passing arguments to pam. Maybe you have somewhere (in Dirac?) example of passing args to pam for the new runtest >

**Comment by bast** [comment]
Indeed, it does not seem obvious at all on how to pass arguments on a per-test basis. I need to look into that.

**Comment by bast** [comment]
OK now reminding myself that you can pass extra args to the run function:
https://github.com/bast/runtest/blob/master/runtest/run.py#L1

**Comment by miroi** [comment]
Excellent ! Now my Dirac extended test script works again. Closing  this ticket as solved.
