### ISSUE TITLE
Example of passing arguments to pam

### ISSUE THREAD

**Issue by miroi** [bast/runtest#17]
Hi Rado,

in https://runtest.readthedocs.io/en/latest/creating/example.html : would it be please possible to add an example of passing arguments to pam ? Like *pam --mw=... *

It don't see how it can be done with newest runtest....

**Comment by miroi** [comment]
I have to search how to pass arguments ....
~~~
# run simple SCF run with calculating dipole moment as expectation value
ierr += run(options,
            configure,
            input_files=['BeH.x2c_scf_dipmom.inp','BeH.sto-2g.C2v.mol'],
            args='--noarch --put "DFPCMO.BeH.x2c_scf_sto-2g.C2v=DFPCMO"',
            filters={'out': f})
.
.
.
milias@lxir127.gsi.de:~/Work/qch/software/dirac/trunk/test/ffpt_dipmom_polariz_relcc/../test -b ~/Work/qch/software/dirac/trunk/build_intelmkl_i8_xh
Traceback (most recent call last):
  File "./test", line 26, in <module>
    filters={'out': f})
TypeError: run() got an unexpected keyword argument 'args'
~~~

**Comment by bast** [comment]
We need better documentation on how to do this - I agree with you.

**Comment by miroi** [comment]
Well, again I need to pass arguments, and have to look into the code....

**Comment by miroi** [comment]
And found it there, https://github.com/bast/runtest/blob/master/runtest/run.py

**Comment by bast** [comment]
This is now documented: http://runtest.readthedocs.io/en/latest/creating/run_function.html
