### ISSUE TITLE
pam --replace and output files

### ISSUE THREAD

**Issue by miroi** [bast/runtest#18]
Hi Rado,

in test file I used scheme for replacing arguments of pam, http://diracprogram.org/doc/master/pam/replace.html , what is causing change of file names.

As I see, runtest expects traditional file name, not names containing replaced striungs, in my case
BeH.x2c_scf_relcc_ffz_BeH.sto-2g.C2v_zff=-0.0005.out  
BeH.x2c_scf_relcc_ffz_BeH.sto-2g.C2v_zff=+0.0005.out

~~~
milias@lxir127.gsi.de:~/Work/qch/software/dirac/trunk/test/ffpt_dipmom_polariz_relcc/../test -b ~/Work/qch/software/dirac/trunk/build_intelmkl_i8_xh

running test with input files ['BeH.x2c_scf_relcc_ffz.inp', 'BeH.sto-2g.C2v.mol'] and args --noarch --replace zff=+0.0005 --put "DFPCMO.BeH.x2c_scf_sto-2g.C2v=DFPCMO"
ERROR: could not open file /u/milias/Work/qch/software/dirac/trunk/test/ffpt_dipmom_polariz_relcc/BeH.x2c_scf_relcc_ffz_BeH.sto-2g.C2v.out
milias@lxir127.gsi.de:~/Work/qch/software/dirac/trunk/test/ffpt_dipmom_polariz_relcc/.
~~~

**Comment by bast** [comment]
I understand the problem. Need to think about how to accommodate this.

**Comment by bast** [comment]
So the problem here is that we tell runtest how to construct the output file name from input file names in the configure function. The solution is I believe to modify DIRAC's configure function to look at extra_args and if they contain replace, then it needs to modify the output_prefix. Do you agree?

**Comment by miroi** [comment]
Agree with that.

**Comment by bast** [comment]
Great - closing this issue.
