### ISSUE TITLE
test --dry-run ?

### ISSUE THREAD

**Issue by miroi** [bast/runtest#19]
Hi Rado,

wouldn't you please consider adding "--dry-run" flag for test to achieve running of jobs, but not comparing against reference files (these could be missing, so one needs to generate them first).

**Comment by bast** [comment]
I think this is a good idea. Not sure about the name `--dry-run`. For me a dry run is one that does not generate any files. So we probably need a different name but the idea is good.

**Comment by bast** [comment]
You can now achieve this with `--skip-verification`.

**Comment by bast** [comment]
Sorry, will rename to `--no-verification`.

**Comment by miroi** [comment]
Rado, I need this feature in DIRAC as I am introducing new tests. Any help ?

**Comment by bast** [comment]
It does not work? http://runtest.readthedocs.io/en/latest/running/command_line_arguments.html#n-no-verification

**Comment by miroi** [comment]
maybe I was wrong, "reclosing" this ticket...
