### ISSUE TITLE
Add test for strings without any numbers

### ISSUE THREAD

**Issue by bast** [bast/runtest#3]

**Comment by miroi** [comment]
Hi Rado,

you mean comparing pure strings which could include some digits ?  

For example, in this DIRAC test I am comparing strings only, https://testboard.org/cdash/testDetails.php?test=4217518&build=28755 .

**Comment by bast** [comment]
Yes. Initially runtest was not designed to test strings specifically but I have seen people using this byproduct-feature. Therefore we need a test to preserve this functionality in future. Or, if we decide
to remove this in future, at least we do it knowingly.
