### ISSUE TITLE
ignore_sign and ignore_order do not seem to work together well

### ISSUE THREAD

**Issue by miroi** [bast/runtest#32]
Hello Rado,

in your test https://github.com/bast/runtest/tree/master/runtest/test/ignore_order you ignore order of numbers in one line.

Bu in the DIRAC issue, https://gitlab.com/dirac/dirac/-/merge_requests/643#note_561951893  , the numbers are in (3rd and 4th) column.

Well, is the feature working also for numbers in columns ? See also https://github.com/bast/runtest/issues/20 .

**Comment by bast** [comment]
hi Miro, I will have a look and think what we can do. I will come back tomorrow with some ideas.

**Comment by miroi** [comment]
I just switched order of numbers in  out.txt, ref.txt (runtest/runtest/test/ignore_order) - they are in columns, and test "runtest/check.py::test_check_ignore_order PASSED".

**Comment by miroi** [comment]
Maybe we need to setup a test as is in DIRAC (https://gitlab.com/dirac/dirac/-/merge_requests/643 ) with "mask" ...
~~~
f = [
    get_filter(from_string='Printout of all property elements',
               to_string   = 'Transformation ended at',
               ignore_sign = True, ignore_order=True,
               mask=[3, 4], # skip first two indexes
               abs_tolerance   = 5.0e-8)
]
~~~

**Comment by miroi** [comment]
Well, here is the DIRAC test case. Numbers are the same in columns, but have different positions (1,5 vs 1,6 etc).

This needs to be fixed in runtest, which must serve also for comparing of numbers from degenerate cases like this one.

~~~
    1    1   0.000000E+00   0.000000E+00
    1    2   0.000000E+00   0.000000E+00
    1    3   0.000000E+00   0.000000E+00
    1    4   0.000000E+00   0.000000E+00
    1    5  -8.046811E-03   0.000000E+00
    1    6   0.000000E+00  -0.000000E+00
    1    7   0.000000E+00   0.000000E+00
    1    8   0.000000E+00   0.000000E+00
    1    9   0.000000E+00   0.000000E+00
    1   10  -0.000000E+00   0.000000E+00
    2    1   0.000000E+00   0.000000E+00
    2    2   0.000000E+00   0.000000E+00
    2    3   0.000000E+00   0.000000E+00
    2    4   0.000000E+00   0.000000E+00
    2    5   1.784654E-02   0.000000E+00
    2    6   0.000000E+00  -0.000000E+00
    2    7   0.000000E+00   0.000000E+00
    2    8   0.000000E+00   0.000000E+00
    2    9   0.000000E+00   0.000000E+00
    2   10  -0.000000E+00   0.000000E+00
    3    1   0.000000E+00   0.000000E+00
    3    2   0.000000E+00   0.000000E+00
    3    3   0.000000E+00   0.000000E+00
    3    4   0.000000E+00   0.000000E+00
    3    5   0.000000E+00   0.000000E+00
    3    6   0.000000E+00   0.000000E+00
    3    7   0.000000E+00   0.000000E+00
    3    8  -8.046811E-03   0.000000E+00
~~~

vs

~~~
    1    1   0.000000E+00   0.000000E+00
    1    2   0.000000E+00   0.000000E+00
    1    3   0.000000E+00   0.000000E+00
    1    4   0.000000E+00   0.000000E+00
    1    5   0.000000E+00  -0.000000E+00
    1    6   8.046811E-03   0.000000E+00
    1    7   0.000000E+00   0.000000E+00
    1    8   0.000000E+00   0.000000E+00
    1    9   0.000000E+00   0.000000E+00
    1   10  -0.000000E+00   0.000000E+00
    2    1   0.000000E+00   0.000000E+00
    2    2   0.000000E+00   0.000000E+00
    2    3   0.000000E+00   0.000000E+00
    2    4   0.000000E+00   0.000000E+00
    2    5   0.000000E+00  -0.000000E+00
    2    6   1.784654E-02   0.000000E+00
    2    7   0.000000E+00   0.000000E+00
    2    8   0.000000E+00   0.000000E+00
    2    9   0.000000E+00   0.000000E+00
    2   10  -0.000000E+00   0.000000E+00
    3    1   0.000000E+00   0.000000E+00
    3    2   0.000000E+00   0.000000E+00
    3    3   0.000000E+00   0.000000E+00
    3    4   0.000000E+00   0.000000E+00
    3    5   0.000000E+00   0.000000E+00
    3    6   0.000000E+00   0.000000E+00
    3    7   0.000000E+00   0.000000E+00
    3    8   0.000000E+00   0.000000E+00
    3    9   8.046811E-03   0.000000E+00
~~~

**Comment by bast** [comment]
Yes good idea about the `mask`. One could set up multiple filters, using `mask`, each for one column, and combine this with ignoring order. I thing this would do it.

And it could be achieved without code duplication by iterating over the column number.

**Comment by miroi** [comment]
Rado, these two columns - 3 and 4 - must be together, as these are complex numbers.  How to setup the filter for such case ?

**Comment by bast** [comment]
But they can still be verified separately, no? I will think a bit on how we could test it better.

**Comment by miroi** [comment]
yes, they can be verified separately, real parts and imaginary parts, each independed on order

**Comment by bast** [comment]
Then the simplest could be to check them separately. I am sure there is a more elegant way but we should think about it. So if you have suggestions for a better interface to make this easier, I am very interested in that.

**Comment by miroi** [comment]
Rado, how about to print all nonzero matrix elements a single line ? Comparing these numbers against  reference with ignoring order should help...

**Comment by bast** [comment]
Good idea. They can also contain zero. One could first filter out (ignore_below) all nonzero, then compare by ignoring order.

**Comment by miroi** [comment]
Like this test, https://github.com/bast/runtest/tree/master/runtest/test/ignore_order , you could a new test ignore_order_and_ignore_sign ...

**Comment by miroi** [comment]
Ad: https://runtest.readthedocs.io/en/latest/creating/filter_options.html#how-to-ignore-the-order-of-numbers ... it must be stressed in the documentation that all the compared numbers are in single like; not in several lines...

**Comment by bast** [comment]
> Rado, `ignore_sign AND ignore_order` do not work together , should be check it via own runtest test...

Yes I agree. I will allow/fix this combination and this can indeed be tested within runtest.
