### ISSUE TITLE
Ignoring very small numbers

### ISSUE THREAD

**Issue by miroi** [bast/runtest#4]
Hi Rado,

Ad: https://runtest.readthedocs.org/en/latest/doc/filter_options.html#how-to-ignore-very-small-or-very-large-numbers

Are signs taken into account ? For example, https://testboard.org/cdash/testDetails.php?test=4218317&build=28793 , I need to neglect both positive and negative numbers, close to zero.

**Comment by bast** [comment]
The code ignores the sign in this case:
https://github.com/bast/runtest/blob/master/src/runtest.py#L95-L99

**Comment by miroi** [comment]
Fine; it couldn't find this in the manual, so I was asking. Would be good to add it to the documentation.
