### ISSUE TITLE
Appveyor for runtest ?

### ISSUE THREAD

**Issue by miroi** [bast/runtest#7]
Hi,

there is only the travis CI service employed. Because runtest (in DIRAC) is used under MS Windows as well, would you agree to include appveyor CI service for runtest ?

**Comment by bast** [comment]
I agree that this is a good idea and will add Appveyor testing soon.

**Comment by miroi** [comment]
Hi,

working on it, https://github.com/miroi/runtest/blob/master/appveyor.yml , will (soon) make PR.
