### ISSUE TITLE
How to test numbers where the order does not matter and the order can change?

### ISSUE THREAD

**Issue by miroi** [bast/runtest#8]
Hi,
see this link: https://testboard.org/cdash/testDetails.php?test=7945159&build=63939
It gives the error because of the degeneracy of p-shells, what gives variously placed reference numbers, which are otherwise correct.

In situations like this for runtest comparison there will be more "configurations" of checked results. How to deal with that ?

**Comment by bast** [comment]
Currently runtest cannot treat such cases. Do you have a good suggestion on how this could be solved?

**Comment by miroi** [comment]
no suggestion...only replace the reference output file, what I did before a while

**Comment by bast** [comment]
If you have a good suggestion about how you would like runtest to behave in such situations, then I am all ears. Until then I am closing the issue.

**Comment by miroi** [comment]
Hi Rado,

now got idea: allow several output files to be checked instead of the default, one output file.

This would mean some extra parameter for *test.run()* to handle several output files. 

Comments ?

**Comment by bast** [comment]
Thank you. I will think about it. Alternative is that we have the possibility to compare list of numbers where the order does not matter.

**Comment by miroi** [comment]
Hi Rado,

I am in big need of this feature.  Suitable way is comparing list of numbers where the order does not matter.

**Comment by bast** [comment]
OK I missed this discussion because the issue is closed. Reopening for the moment.

**Comment by bast** [comment]
So what you suggest is that we compare a list and let it pass only if the set is the same but the order does not matter?

**Comment by miroi** [comment]
Yes, let it checks numbers only (in specific column) without order.

**Comment by bast** [comment]
I think this is a good idea and should become a new filter option.

**Comment by bast** [comment]
This can now be achieved with `ignore_order=True`.
